"use client";
import { useState } from "react";
import { BadgeCheck,Check,Clock3,CreditCard,MapPin } from "lucide-react";
import { Card,PageHeader,PrimaryButton,SecondaryButton,SecureFooter } from "../../ui";
import { cma } from "@/lib/mock-data";
import { ScreenId } from "../registry";
import { Shell, Avatar, Option } from "../shared";

export function BookDate({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [d,setD]=useState(1);return <Shell><PageHeader title="Choose a day" subtitle="Available home visits near Miami, Florida." onBack={back} eyebrow="Book a visit"/><div role="radiogroup" aria-label="Visit day" className="grid grid-cols-3 gap-3">{["Tue\nMay 20","Wed\nMay 21","Thu\nMay 22","Fri\nMay 23","Sat\nMay 24","Mon\nMay 26"].map((x,i)=><button onClick={()=>setD(i)} key={x} role="radio" aria-checked={d===i} className={`min-h-14 rounded-[20px] border p-4 whitespace-pre-line text-sm ${d===i?"border-brand-teal bg-[#edfbfa] font-extrabold ring-1 ring-inset ring-brand-teal":"border-[#dfe9eb] bg-white font-bold"}`}>{x}</button>)}</div><Card className="mt-5 flex gap-3 p-4"><MapPin className="text-teal-ink"/><div><b className="text-sm">Service address</b><p className="mt-1 text-xs text-slate-500">1420 Brickell Ave, Miami, FL</p></div></Card><div className="mt-7"><PrimaryButton onClick={()=>go("book-time")}>Choose a time</PrimaryButton></div></Shell>}
export function BookTime({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(1);return <Shell><PageHeader title="Choose a time" subtitle="Wednesday, May 21" onBack={back} eyebrow="Book a visit"/><div className="space-y-3">{["8:00–9:00 AM","9:00–10:00 AM","10:00–11:00 AM","11:00 AM–12:00 PM","1:00–2:00 PM"].map((x,i)=><Option key={x} title={x} sub={i===1?"Best availability":"1-hour arrival window"} active={a===i} onClick={()=>setA(i)} icon={Clock3}/>)}</div><div className="mt-7"><PrimaryButton onClick={()=>go("payment")}>Review and pay</PrimaryButton></div></Shell>}
export function Payment({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Review your visit" subtitle="You won’t be charged again without approval." onBack={back} eyebrow="Secure checkout"/><Card className="p-5"><div className="flex justify-between"><div><b>At-home diagnostic visit</b><p className="mt-1 text-xs text-slate-500">Wed, May 21 · 9:00–10:00 AM</p></div><b>$99</b></div><div className="my-5 border-t border-[#e5eeee]"/><div className="flex justify-between text-sm"><span className="text-slate-500">Total today</span><b className="text-xl">$99.00</b></div></Card><h3 className="mb-3 mt-6 font-extrabold">Payment method</h3><Card className="flex items-center gap-3 p-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#f0f5f7]"><CreditCard/></span><div className="flex-1"><b className="text-sm">Visa ending in 4242</b><p className="text-xs text-slate-500">Expires 08/29</p></div><Check className="text-teal-ink"/></Card><label className="mt-5 flex gap-3 text-sm leading-6 text-slate-500"><input type="checkbox" defaultChecked className="mt-1 accent-[#12aaa5]"/>I agree to the Terms of Service and acknowledge the Notice of Privacy Practices.</label><div className="mt-7"><PrimaryButton onClick={()=>go("confirmed")}>Pay $99 and confirm</PrimaryButton></div><SecureFooter/></Shell>}
export function Confirmed({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><div className="pt-8 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#dff6f4] text-teal-ink"><BadgeCheck size={42}/></div><h1 className="mt-6 text-3xl font-extrabold">You’re all set!</h1><p className="mt-2 text-slate-500">Your visit is confirmed.</p></div><Card className="mt-7 overflow-hidden"><div className="bg-brand-navy p-5 text-white"><span className="text-xs uppercase tracking-widest text-white/60">Upcoming visit</span><h2 className="mt-2 text-xl font-extrabold">Wednesday, May 21</h2><p className="mt-1 text-sm text-white/70">9:00–10:00 AM</p></div><div className="p-5"><div className="flex items-center gap-3"><Avatar/><div><b>{cma.name}</b><p className="text-xs text-slate-500">Your Certified Medical Assistant</p></div></div></div></Card><div className="mt-5"><PrimaryButton onClick={()=>go("assigned")}>Track your visit</PrimaryButton></div><div className="mt-3"><SecondaryButton onClick={back}>Add to calendar</SecondaryButton></div></Shell>}
