"use client";
import { useState } from "react";
import { Check,PackageCheck } from "lucide-react";
import { Card,PageHeader,PrimaryButton } from "../../ui";
import { devices } from "@/lib/mock-data";
import { ScreenId } from "../registry";
import { Shell } from "../shared";

export function Compare({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(0);return <Shell><PageHeader title="Compare your options" subtitle="All devices are clinically appropriate for your results." onBack={back} eyebrow="Device selection"/><div className="space-y-3">{devices.map((d,i)=><button onClick={()=>setA(i)} key={d.name} className={`w-full rounded-[22px] border bg-white p-4 text-left ${a===i?"border-brand-teal":"border-[#dfe9eb]"}`}><div className="flex items-start justify-between"><div><span className="text-[10px] font-extrabold uppercase tracking-widest text-brand-teal">{d.badge}</span><h3 className="mt-1 font-extrabold">{d.name}</h3><p className="mt-1 text-sm text-slate-500">{d.price}</p></div><span className={`grid h-6 w-6 place-items-center rounded-full border ${a===i?"border-brand-teal bg-brand-teal text-white":"border-slate-300"}`}>{a===i&&<Check size={15}/>}</span></div><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-[#e4ecec]"><div className="h-full rounded-full bg-brand-teal" style={{width:`${d.fit}%`}}/></div><b className="text-xs">{d.fit}% fit</b></div></button>)}</div><div className="mt-6"><PrimaryButton onClick={()=>go("checkout")}>Choose {devices[a].name}</PrimaryButton></div></Shell>}
export function Checkout({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Complete your order" subtitle="Your audiologist’s recommendation is attached automatically." onBack={back} eyebrow="Secure checkout"/><Card className="p-5"><div className="flex items-center gap-4"><div className="h-20 w-16 rounded-[30px] bg-gradient-to-b from-[#ded7ca] to-[#9f978b]"/><div className="flex-1"><b>Phonak Audéo L50</b><p className="mt-1 text-xs text-slate-500">Pair · Champagne</p></div><b>$1,590</b></div><div className="my-5 border-t border-[#e5eeee]"/><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Device pair</span><span>$1,590</span></div><div className="flex justify-between"><span className="text-slate-500">Remote fitting</span><span>Included</span></div><div className="flex justify-between"><span className="text-slate-500">Shipping</span><span>Free</span></div><div className="flex justify-between pt-2 text-lg font-extrabold"><span>Total</span><span>$1,590</span></div></div></Card><Card className="mt-4 flex gap-3 p-4"><PackageCheck className="text-brand-teal"/><div><b className="text-sm">30-day care guarantee</b><p className="mt-1 text-xs leading-5 text-slate-500">Includes delivery, activation, fitting, and follow-up support.</p></div></Card><div className="mt-6"><PrimaryButton onClick={()=>go("order")}>Place order</PrimaryButton></div></Shell>}
export function Order({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Your order is confirmed" subtitle="We’ll keep you updated at every step." onBack={back} eyebrow="Order HM-84721"/><div className="rounded-[28px] bg-brand-navy p-6 text-white"><div className="grid h-14 w-14 place-items-center rounded-full bg-white/10"><PackageCheck size={29}/></div><h2 className="mt-5 text-2xl font-extrabold">Estimated delivery<br/>May 24–26</h2><p className="mt-2 text-sm text-white/65">Free insured shipping</p></div><Card className="mt-4 p-5"><div className="space-y-6">{[["Order received","Today · 11:42 AM",true],["Clinical configuration","In progress",true],["Shipped","Next",false],["Delivered & activated","Pending",false]].map(([t,s,done]:any,i)=><div key={t} className="flex gap-4"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${done?"bg-brand-teal text-white":"bg-[#edf2f2] text-slate-400"}`}>{done?<Check size={16}/>:i+1}</span><div><b className={done?"":"text-slate-400"}>{t}</b><p className="mt-1 text-xs text-slate-500">{s}</p></div></div>)}</div></Card><div className="mt-6"><PrimaryButton onClick={()=>go("support")}>View support plan</PrimaryButton></div></Shell>}
