"use client";
import { Star } from "lucide-react";
import { Card,PageHeader,PrimaryButton,SecondaryButton,StatusPill } from "../../ui";
import { cma } from "@/lib/mock-data";
import { ScreenId } from "../registry";
import { Shell, Avatar, RouteMap } from "../shared";

export function Assigned({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell dark><PageHeader title="Maya is assigned" subtitle="Your care team is ready for your visit." onBack={back} eyebrow="Visit status"/><RouteMap/><Card className="mt-4 p-4 text-brand-navy"><div className="flex flex-wrap items-center gap-3"><Avatar/><div className="min-w-0 flex-1"><b>{cma.name}</b><p className="text-xs text-slate-500">Certified Medical Assistant</p><p className="mt-1 flex items-center gap-1 text-xs"><Star size={13} fill="currentColor"/> 4.9 · 128 visits</p></div><StatusPill tone="green">Confirmed</StatusPill></div><div className="mt-4 grid grid-cols-2 gap-2"><SecondaryButton>Message</SecondaryButton><SecondaryButton>Call</SecondaryButton></div></Card><div className="mt-4"><PrimaryButton onClick={()=>go("driving")}>Simulate visit day</PrimaryButton></div></Shell>}
export function Driving({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell dark><PageHeader title="Maya is on the way" subtitle="We’ll notify you when she arrives." onBack={back} eyebrow="Live tracking"/><RouteMap moving/><Card className="mt-4 p-5 text-brand-navy"><span className="text-xs font-bold uppercase tracking-widest text-teal-ink">Estimated arrival</span><div className="mt-1 flex items-end justify-between"><b className="text-4xl">12 <span className="text-lg">min</span></b><span className="text-xs text-slate-500">8.4 miles away</span></div></Card><div className="mt-4"><PrimaryButton onClick={()=>go("arrived")}>Maya has arrived</PrimaryButton></div></Shell>}
export function Arrived({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell dark><PageHeader title="Maya has arrived" subtitle="She’ll let you know when it’s time to begin." onBack={back} eyebrow="At your home"/><div className="rounded-[28px] bg-gradient-to-br from-[#16426c] to-[#0c2340] p-7 text-center"><Avatar large/><h2 className="mt-4 text-2xl font-extrabold">Welcome Maya</h2><p className="mt-2 text-sm text-white/65">Please confirm the visitor photo and name before opening the door.</p></div><Card className="mt-4 p-5 text-brand-navy"><div className="flex justify-between"><span className="text-sm text-slate-500">Visit ID</span><b>HM-0521-1092</b></div><div className="mt-3 flex justify-between"><span className="text-sm text-slate-500">Kit ID</span><b>KIT-MIA-014</b></div></Card><div className="mt-4"><PrimaryButton onClick={()=>go("consent")}>Start the visit</PrimaryButton></div></Shell>}
