"use client";
import { Clock, Star } from "lucide-react";
import { Card,PageHeader,PrimaryButton,SecondaryButton,StatusPill } from "../../ui";
import { appointment, arrival, cma } from "@/lib/mock-data";
import { dayShort, useBookingDay } from "@/lib/booking-days";
import { ScreenId } from "../registry";
import { Shell, Avatar, AudiologistStatusLine, OnTheWayNotice } from "../shared";

// No map and no live position (Issac, 2026-10-05: caregivers don't like being
// tracked). The patient is told what will happen on visit day — a message
// when Maya sets off, with an arrival time — and nothing about where she is.
export function Assigned({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const day=useBookingDay();return <Shell><PageHeader title="Maya is assigned" subtitle={`She’ll visit you on ${dayShort(day)}, ${appointment.time}.`} onBack={back} eyebrow="Visit status"/><Card className="p-4 text-brand-navy"><div className="flex flex-wrap items-center gap-3"><Avatar/><div className="min-w-0 flex-1"><b>{cma.name}</b><p className="text-xs text-slate-500">Certified Medical Assistant</p><p className="mt-1 flex items-center gap-1 text-xs"><Star size={13} fill="currentColor"/> 4.9 · 128 visits</p></div><StatusPill tone="green">Confirmed</StatusPill></div><div className="mt-4 grid grid-cols-2 gap-2"><SecondaryButton>Message</SecondaryButton><SecondaryButton>Call</SecondaryButton></div></Card><div className="mt-4 rounded-[26px] bg-[#eef7f7] p-5"><span className="text-xs font-bold uppercase tracking-widest text-teal-ink">On visit day</span><p className="mt-2 text-[15px] leading-6 text-brand-navy">We’ll send you a message when Maya sets off, with the time she’ll arrive.</p><OnTheWayNotice className="mt-4"/></div><div className="mt-4"><PrimaryButton onClick={()=>go("driving")}>Simulate visit day</PrimaryButton></div></Shell>}
// The patient's screen carries no button for a clinical act someone else
// performs — here, Maya arriving. The chrome's Next advances the story
// instead. The subtitle already says "We'll notify you when she arrives", so
// no extra status line is added; the button is simply dropped.
export function Driving({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Maya is on her way" subtitle="We’ll let you know when she’s at your door." onBack={back} eyebrow="Visit day"/><OnTheWayNotice/><Card className="mt-4 p-6 text-center text-brand-navy"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#e8f9f8] text-teal-ink"><Clock size={26}/></span><span className="mt-4 block text-xs font-bold uppercase tracking-widest text-teal-ink">Estimated arrival</span><b className="mt-1 block text-4xl">{arrival.eta}</b><p className="mt-1 text-sm text-slate-500">In about {arrival.minutes} minutes</p></Card><Card className="mt-4 p-4 text-brand-navy"><div className="flex items-center gap-3"><Avatar/><div className="min-w-0 flex-1"><b>{cma.name}</b><p className="text-xs text-slate-500">Certified Medical Assistant</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><SecondaryButton>Message</SecondaryButton><SecondaryButton>Call</SecondaryButton></div></Card></Shell>}
// Same reasoning as Driving. Starting the visit is Maya's act, not Alex's, so
// the button is replaced with a status line naming who acts next, matching
// AudiologistStrip's visual language elsewhere in this flow.
export function Arrived({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Maya has arrived" subtitle="She’ll let you know when it’s time to begin." onBack={back} eyebrow="At your home"/><div className="rounded-[28px] bg-gradient-to-br from-[#16426c] to-[#0c2340] p-7 text-center text-white"><Avatar large/><h2 className="mt-4 text-2xl font-extrabold">Welcome Maya</h2><p className="mt-2 text-sm text-white/65">Please confirm the visitor photo and name before opening the door.</p></div><Card className="mt-4 p-5 text-brand-navy"><div className="flex justify-between"><span className="text-sm text-slate-500">Visit ID</span><b>HM-0521-1092</b></div><div className="mt-3 flex justify-between"><span className="text-sm text-slate-500">Kit ID</span><b>KIT-MIA-014</b></div></Card><AudiologistStatusLine className="mt-4">Maya will start the visit when you’re ready.</AudiologistStatusLine></Shell>}
