"use client";
import { useState } from "react";
import { Check,FileHeart,Phone,Stethoscope,Video,Volume2 } from "lucide-react";
import { Card,PageHeader,PrimaryButton } from "../../ui";
import { BRAND_NAME } from "@/lib/mock-data";
import { OtoscopyStep } from "../../exam/otoscopy-step";
import { TympanometryStep } from "../../exam/tympanometry-step";
import { PureToneStep } from "../../exam/puretone-step";
import { ScreenId } from "../registry";
import { Shell } from "../shared";

// The visit's patient-facing steps, counted from one list so adding a step
// (as tympanometry was, corrections sheet item 5) renumbers every eyebrow —
// a hardcoded "N of 5" is exactly what lib/regressions.test.ts bans.
const VISIT_FLOW = ["setup", "otoscopy", "tympanometry", "testing", "live"] as const;
const visitEyebrow = (id: (typeof VISIT_FLOW)[number]) =>
  `Visit ${VISIT_FLOW.indexOf(id) + 1} of ${VISIT_FLOW.length}`;

export function Consent({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [ok,setOk]=useState(true);return <Shell><PageHeader title="Before we begin" subtitle="Please review and confirm today’s visit consent." onBack={back} eyebrow="Patient consent"/><Card className="p-5"><h3 className="font-extrabold">Today’s session may include</h3><div className="mt-4 space-y-4">{[[Video,"Secure video with your audiologist"],[FileHeart,"Clinical test data and images"],[Volume2,"Optional session recording for care quality"]].map(([I,t]:any)=><div key={t} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f7] text-brand-teal"><I size={19}/></span><span className="text-sm font-semibold">{t}</span></div>)}</div></Card><button onClick={()=>setOk(!ok)} className="mt-4 flex w-full items-start gap-3 rounded-2xl bg-white p-4 text-left"><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-md border ${ok?"border-brand-teal bg-brand-teal text-white":"border-slate-300"}`}>{ok&&<Check size={15}/>}</span><span className="text-sm leading-6 text-slate-600">I understand and consent to the use of my information for this hearing-care visit.</span></button><div className="mt-6"><PrimaryButton disabled={!ok} onClick={()=>go("setup")}>Confirm and continue</PrimaryButton></div></Shell>}
export function Setup({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title={`Preparing the ${BRAND_NAME} kit`} subtitle="Maya is completing the safety and equipment checklist." onBack={back} eyebrow={visitEyebrow("setup")}/><div className="grid place-items-center rounded-[30px] bg-gradient-to-br from-[#e7f8f7] to-white py-10"><div className="relative h-36 w-56 rounded-[28px] bg-brand-navy shadow-card"><div className="absolute inset-x-8 top-8 h-16 rounded-xl bg-[#e6f7f6]"/><div className="absolute bottom-5 left-1/2 h-4 w-20 -translate-x-1/2 rounded-full bg-[#183b5e]"/></div></div><div className="mt-5 space-y-3">{["Kit identity verified","Equipment calibration current","Single-use items prepared","Room noise level acceptable"].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white p-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dcf5ef] text-emerald-600"><Check size={16}/></span><b className="text-sm">{x}</b></div>)}</div><div className="mt-6"><PrimaryButton onClick={()=>go("otoscopy")}>Begin ear check</PrimaryButton></div></Shell>}
// Two captures, one per ear (corrections sheet 2026-08-31, item 3) — the
// shared step renders both, so patient and CMA can never drift apart.
export function Otoscopy({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Ear health check" subtitle="Maya is capturing a secure image of each ear for clinical review." onBack={back} eyebrow={visitEyebrow("otoscopy")}/><OtoscopyStep framing="patient"/><Card className="mt-4 flex gap-3 p-4"><Stethoscope className="text-brand-teal"/><p className="text-sm leading-6 text-slate-500">Images are reviewed by your licensed audiologist and stored with today’s clinical record.</p></Card><div className="mt-6"><PrimaryButton onClick={()=>go("tympanometry")}>Start middle ear check</PrimaryButton></div></Shell>}
// New step (corrections sheet 2026-08-31, item 5): tympanometry between the
// ear health check and the hearing test, on every exam.
export function Tympanometry({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Middle ear check" subtitle="A gentle pressure test of each eardrum — nothing to do but sit still." onBack={back} eyebrow={visitEyebrow("tympanometry")}/><TympanometryStep framing="patient"/><div className="mt-6"><PrimaryButton onClick={()=>go("testing")}>Start hearing test</PrimaryButton></div></Shell>}
export function Testing({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell><PageHeader title="Hearing test in progress" subtitle="Tap the button whenever you hear a tone, even if it is very soft." onBack={back} eyebrow={visitEyebrow("testing")}/><PureToneStep framing="patient"/><div className="mt-6"><PrimaryButton onClick={()=>go("live")}>Complete test</PrimaryButton></div></Shell>}
export function Live({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <Shell dark><PageHeader title="Connected to your audiologist" subtitle="Dr. Susan Reed is reviewing your test in real time." onBack={back} eyebrow={visitEyebrow("live")}/><div className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#e9f4f1] to-[#bddeea] pt-10 text-center text-brand-navy"><div className="mx-auto grid h-36 w-36 place-items-center rounded-full bg-white text-4xl font-extrabold shadow-card">SR</div><h2 className="mt-5 text-xl font-extrabold">Dr. Susan Reed, Au.D.</h2><p className="mt-1 text-sm text-slate-500">Licensed Audiologist · Florida</p><div className="mt-8 flex justify-center gap-4 bg-white/70 py-5"><button className="grid h-14 w-14 place-items-center rounded-full bg-white"><Volume2/></button><button className="grid h-14 w-14 place-items-center rounded-full bg-white"><Video/></button><button onClick={()=>go("review")} className="grid h-14 w-14 place-items-center rounded-full bg-red-500 text-white"><Phone className="rotate-[135deg]"/></button></div></div><p className="mt-5 flex items-center justify-center gap-2 text-sm text-[#8be0d8]"><span className="h-2 w-2 rounded-full bg-[#47d0c4]"/>Secure clinical connection</p><div className="mt-5"><PrimaryButton onClick={()=>go("review")} className="bg-brand-teal">Finish consultation</PrimaryButton></div></Shell>}
