"use client";
import { useState } from "react";
import { Activity,BadgeCheck,CreditCard,FileHeart,HeartPulse,Home,ShieldCheck,Sparkles,Stethoscope,UserRound,Video,WalletCards } from "lucide-react";
import { Card,StatusPill } from "../../ui";
import { BRAND_NAME, patient } from "@/lib/mock-data";
import { ScreenId } from "../registry";
import { Option, StepPage } from "../shared";

export function IntakeFor({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(0);return <StepPage title="Who is the visit for?" subtitle="You can book for yourself or someone you care for." step={1} onBack={back} onNext={()=>go("intake-needs")}><Option title="Myself" sub="I am the patient" icon={UserRound} active={a===0} onClick={()=>setA(0)}/><Option title="A family member" sub="I’ll help manage their care" icon={HeartPulse} active={a===1} onClick={()=>setA(1)}/></StepPage>}
export function IntakeNeeds({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(0);return <StepPage title="What are you noticing?" subtitle="Choose the main issue. You can add more later." step={2} onBack={back} onNext={()=>go("intake-medical")}><Option title="Speech is unclear" sub="Especially in groups or background noise" active={a===0} onClick={()=>setA(0)}/><Option title="TV or phone volume is too high" active={a===1} onClick={()=>setA(1)}/><Option title="Ringing in the ears" active={a===2} onClick={()=>setA(2)}/><Option title="A recent change in hearing" active={a===3} onClick={()=>setA(3)}/></StepPage>}
export function IntakeMedical({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(1);return <StepPage title="A quick safety check" subtitle="This helps us identify symptoms that may need medical attention first." step={3} onBack={back} onNext={()=>go("intake-coverage")}><Option title="No urgent symptoms" sub="No sudden loss, pain, drainage, or severe dizziness" icon={BadgeCheck} active={a===1} onClick={()=>setA(1)}/><Option title="I have one of these symptoms" sub="We’ll guide you to the right clinical next step" icon={Stethoscope} active={a===0} onClick={()=>setA(0)}/><Card className="flex gap-3 p-4"><Sparkles className="text-brand-teal"/><p className="text-sm leading-6 text-slate-500">{`${BRAND_NAME} does not replace emergency or ENT care. Red flags are reviewed before scheduling.`}</p></Card></StepPage>}
export function IntakeCoverage({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){const [a,setA]=useState(0);return <StepPage title="How will you pay?" subtitle="Your $99 visit is self-pay. We can help you request reimbursement." step={4} onBack={back} onNext={()=>go("intake-plan")}><Option title="Use my insurance benefits" sub="We’ll create a personalized Superbill" icon={ShieldCheck} active={a===0} onClick={()=>setA(0)}/><Option title="Self-pay only" sub="No insurance paperwork needed" icon={WalletCards} active={a===1} onClick={()=>setA(1)}/><Option title="I’m not sure yet" sub="You can decide after the visit" icon={CreditCard} active={a===2} onClick={()=>setA(2)}/></StepPage>}
export function IntakePlan({go,back}:{go:(s:ScreenId)=>void;back:()=>void}){return <StepPage title="Your personalized plan" subtitle="Based on your answers, an at-home diagnostic visit is a good fit." step={5} onBack={back} onNext={()=>go("book-date")} next="Choose a visit"><Card className="overflow-hidden"><div className="bg-[#e7f8f7] p-5"><StatusPill>Good match</StatusPill><h2 className="mt-4 text-2xl font-extrabold">At-home hearing diagnostic</h2><p className="mt-2 text-sm leading-6 text-slate-600">A CMA brings the clinical kit. A licensed audiologist joins remotely.</p></div><div className="space-y-4 p-5">{[[Home,"Home visit"],[Activity,"Clinical-grade testing"],[Video,"Audiologist review"],[FileHeart,"Results and care plan"]].map(([Icon,t]:any)=><div key={t} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f1f7f7] text-brand-teal"><Icon size={19}/></span><b className="text-sm">{t}</b></div>)}</div></Card><div className="rounded-2xl bg-brand-navy p-4 text-white"><span className="text-xs text-white/60">Estimated visit price</span><div className="mt-1 flex items-end justify-between"><b className="text-3xl">$99</b><span className="text-xs text-white/70">Superbill available</span></div></div></StepPage>}
