"use client";
import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { BrandLogo } from "./ui";
import { ScreenId, order, labels } from "./screens/registry";
import { BottomNav } from "./screens/shared";
import { Welcome, SignIn, HomeScreen } from "./screens/patient/welcome";
import { IntakeFor, IntakeNeeds, IntakeMedical, IntakeCoverage, IntakePlan } from "./screens/patient/intake";
import { BookDate, BookTime, Payment, Confirmed } from "./screens/patient/booking";
import { Assigned, Driving, Arrived } from "./screens/patient/dispatch";
import { Consent, Setup, Otoscopy, Tympanometry, Testing, Live } from "./screens/patient/exam";
import { Review, Results, Recommendation } from "./screens/patient/results";
import { Compare, Checkout, Order } from "./screens/patient/commerce";
import { Support } from "./screens/patient/support";

export function PatientApp(){const [current,setCurrent]=useState<ScreenId>("welcome");const idx=order.indexOf(current);const go=(s:ScreenId)=>setCurrent(s);const back=()=>setCurrent(order[Math.max(0,idx-1)]);const screens=useMemo(()=>({welcome:<Welcome go={go}/>,signin:<SignIn go={go} back={back}/>,home:<HomeScreen go={go}/>,"intake-for":<IntakeFor go={go} back={back}/>,"intake-needs":<IntakeNeeds go={go} back={back}/>,"intake-medical":<IntakeMedical go={go} back={back}/>,"intake-coverage":<IntakeCoverage go={go} back={back}/>,"intake-plan":<IntakePlan go={go} back={back}/>,"book-date":<BookDate go={go} back={back}/>,"book-time":<BookTime go={go} back={back}/>,payment:<Payment go={go} back={back}/>,confirmed:<Confirmed go={go} back={back}/>,assigned:<Assigned go={go} back={back}/>,driving:<Driving go={go} back={back}/>,arrived:<Arrived go={go} back={back}/>,consent:<Consent go={go} back={back}/>,setup:<Setup go={go} back={back}/>,otoscopy:<Otoscopy go={go} back={back}/>,tympanometry:<Tympanometry go={go} back={back}/>,testing:<Testing go={go} back={back}/>,live:<Live go={go} back={back}/>,review:<Review go={go} back={back}/>,results:<Results go={go} back={back}/>,recommendation:<Recommendation go={go} back={back}/>,compare:<Compare go={go} back={back}/>,checkout:<Checkout go={go} back={back}/>,order:<Order go={go} back={back}/>,support:<Support go={go} back={back}/>} as Record<ScreenId,React.ReactNode>),[current]);return <main><motion.div key={current} initial={{opacity:0,x:14}} animate={{opacity:1,x:0}} transition={{duration:.2}}>{screens[current]}</motion.div><BottomNav current={current} go={go}/><aside className="fixed right-5 top-5 z-40 hidden w-56 rounded-[22px] border border-[#dce8e9] bg-white/95 p-3 shadow-card backdrop-blur xl:block"><div className="mb-3 flex items-center justify-between"><BrandLogo compact/><span className="text-xs font-bold text-slate-400">{idx+1}/{order.length}</span></div><select value={current} onChange={e=>go(e.target.value as ScreenId)} className="w-full rounded-xl border border-[#dce8e9] bg-white p-2 text-xs font-bold outline-none">{order.map(x=><option key={x} value={x}>{`${order.indexOf(x)+1}. ${labels[x]}`}</option>)}</select><p className="mt-3 text-[10px] leading-4 text-slate-400">Demo navigator — jump directly to any MVP screen.</p></aside></main>}
